#!/usr/bin/env bash
# Auto-create / repair VPS .env for srv851550 — no manual editing required.
# Usage: bash scripts/vps/ensure-env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"
SECRETS_FILE="${SECRETS_FILE:-$ROOT/.env.secrets}"

gen_secret() { openssl rand -hex 32; }

read_secret() {
  local key="$1"
  if [ -f "$SECRETS_FILE" ]; then
    # shellcheck disable=SC1090
    local val
    val="$(grep -E "^${key}=" "$SECRETS_FILE" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    if [ -n "$val" ]; then
      echo "$val"
      return
    fi
  fi
  if [ -f "$ENV_FILE" ]; then
    local val
    val="$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- || true)"
    if [ -n "$val" ] && [[ "$val" != *CHANGE_ME* ]] && [ "$val" != "change-me-in-production-min-32-chars" ]; then
      echo "$val"
      return
    fi
  fi
  gen_secret
}

PG_PASS="$(read_secret POSTGRES_PASSWORD)"
JWT_SECRET="$(read_secret JWT_SECRET)"
WEBHOOK_SECRET="$(read_secret WEBHOOK_SIGNING_SECRET)"

mkdir -p "$(dirname "$ENV_FILE")"
cat >"$ENV_FILE" <<EOF
# Auto-generated by scripts/vps/ensure-env.sh — srv851550 / arheb.net
# Re-run: bash scripts/vps/ensure-env.sh (preserves secrets via .env.secrets)

POSTGRES_PASSWORD=${PG_PASS}
DATABASE_URL=postgresql://whatsapp:${PG_PASS}@postgres:5432/whatsapp_sender
REDIS_URL=redis://redis:6379

API_PORT=3010
API_HOST_PORT=3020
WEB_HOST_PORT=3021

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
WEBHOOK_SIGNING_SECRET=${WEBHOOK_SECRET}

CORS_ORIGIN=https://whatsapp.arheb.net
NEXT_PUBLIC_API_URL=https://api.whatsapp.arheb.net
NEXT_PUBLIC_WEB_URL=https://whatsapp.arheb.net

BAILEYS_MOCK=0
WORKER_CONCURRENCY=5

PLATFORM_ADMIN_EMAILS=arheb.invitations@gmail.com
ADMIN_PHONE=201277785111
ADMIN_NOTIFY_ENABLED=1
OTP_DEV_MODE=0
EOF

cat >"$SECRETS_FILE" <<EOF
POSTGRES_PASSWORD=${PG_PASS}
JWT_SECRET=${JWT_SECRET}
WEBHOOK_SIGNING_SECRET=${WEBHOOK_SECRET}
EOF
chmod 600 "$SECRETS_FILE" 2>/dev/null || true

echo "✅ VPS .env ready: $ENV_FILE"
echo "   Secrets persisted: $SECRETS_FILE"
